
// const HOST = 'http://121.42.216.103/testbank'
export const HOST = 'http://www.jedeft.cn/testbank'
export const ACADEMY_LIST = '/admin/academys'
export const MAJOR_LIST = '/admin/majors'
export const TEACHER_LIST = '/admin/teachers'
export const BUILDER_LIST = '/admin/bankBuilders'
export const CLASS_LIST = '/admin/classes'
export const COURSE_LIST = '/admin/courses'
export const STUDENT_LIST = '/admin/students'
export const SCHEDUEL_LIST = '/admin/syllabuses'
