<template>
  <bank-select-set>
    <bank-select
      :index="0"
      :autostart="true"
      prop-id="academy_id"
      info="请选择学院"
      url="/admin/academys"
      :value.sync="academy_id"></bank-select>
  </bank-select-set>
  <bank-title>查看班级信息</bank-title>
  <bank-title>添加班级信息</bank-title>
</template>
